### ISSUE TITLE
findHostIP() sometimes returns unwanted IPs

### ISSUE THREAD

**Issue by apatecturcanu** [wso2-attic/docker-common#12]
When trying to build a docker image the scripts calls the findHostIP-function which tries to select the IP of the machine it's running on. In our case however docker runs on a local IP 172.* which then leads to problems trying to access the platform.

Since it is very hard to write a function which considers such scenarios it would be great if the IP was instead also a parameter. So then instead of always calling the findHostIP-function instead the IP from the parameter would be used (if provided).

**Comment by chamilad** [comment]
Could you elaborate on the exact errors that you come across? I too have the default Docker virtual bridge running on 172* range. Any extra details like the host OS information could greatly help too.

**Comment by apatecturcanu** [comment]
Put simply, since the findHostIP-function returns the 172* range that host will only be accessible from that private network. As far as I know the Docker virtual bridge runs on 172* by default in order to communicate with itself but because this device is the first in line and the findHostIP-function doesn't take this into account the server will always assume that it needs to be in that network.

I'm using RHEL 7.3 with Docker 1.12.6 and WSO2AM 2.1.0
