### ISSUE TITLE
WSO2 API Manager Analytics dockerfile

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [wso2-attic/docker-common#13]
Hello.

There is Analytics for API Manager which works as separate web application. However, I couldn't find dockerfile in this [link](https://github.com/wso2?utf8=%E2%9C%93&q=docker).

In this [page](https://docs.wso2.com/display/AM210/Configuring+APIM+Analytics) documentation says that installing is same as Data Analytics Server.

Does the Data Analytics Server works just as API Manager Analytics? If I install DAS via docker, is it possible to integrate with API Manager?

**Comment by pubudu538** [comment]
Please check - https://github.com/wso2/docker-apim/tree/master/docker-compose/pattern-2

API Manager Analytics is DAS + API Manager Analytics features. If you are using DAS, you need to install API Manager Analytics features (https://docs.wso2.com/display/AM210/Installing+WSO2+APIM+Analytics+Features)
