### ISSUE TITLE
 No such file or directory when running created container

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [wso2-attic/docker-common#15]
Hello. I have been creating docker image for IoTS, by using [this link](https://github.com/wso2/docker-iot/tree/master/dockerfile)

I have placed wso2iot-31.0.zip and JDK tar file in corressponding folders then run `./build.sh -v 3.1.0` and `/run.sh -v 3.1.0` 

After that my machine says that container exited with code 1. Logs shows this:

    Initializing wso2iot-3.1.0 in default profile on default platform...
    sed: can't read /mnt/wso2iot-3.1.0/repository/conf/axis2/axis2.xml: No such file or directory
    Error occurred while updating localMemberHost with 172.17.0.2
    Creating directory /mnt/172.17.0.2
    Creating symlink [Target] /mnt/wso2iot-3.1.0, [Link] /mnt/172.17.0.2/wso2iot-3.1.0
    Starting wso2iot-3.1.0 with [Startup Args] , [CARBON_HOME] /mnt/172.17.0.2/wso2iot-3.1.0
    /usr/local/bin/init.sh: line 132: /mnt/172.17.0.2/wso2iot-3.1.0/bin/wso2server.sh: No such file or directory
    ERROR in /usr/local/bin/init.sh: line 132: exit status of last command: 127

Why this is happening?

**Comment by Jeferex** [comment]
Same here. Did you find a solution?

**Comment by pubudu538** [comment]
Do you get any errors when building the docker image for IOT?

**Comment by SuperMasterBlasterLaser** [comment]
@pubudu538  @Jeferex There were no errors during the building image and I haven't found any solution.

I have just uploaded zip file of iot-server and launched three bash scripts as a service.

**Comment by terajoellang** [comment]
Why is this issue not resolved yet?? I have the same problem. WSO2, please address this problem today or otherwise I will let you know for which company I am working and at the latest then you'll be working on that with very high pressure
