### ISSUE TITLE
Include jdbc-drivers

### ISSUE THREAD

**Issue by davidkarlsen** [wso2-attic/docker-common#8]
The image that is built does include the mysql jdbc driver (or any other, like oracle) - it would be nice to have them readily included in the image, so adaption for the buildscript (to include the contents of a directory and place it in /mnt/wso2am-2.1.0/repository/components/lib would be a great feature.

**Comment by chamilad** [comment]
IMO this should be handled at the child image creation. We have included this scenario in Puppet based Docker image creation where the drivers, the packs, and the other necessary dependencies are downloaded from Puppet Master. A similar pattern/pipeline could be figured out for other tools as well. 

Including these dependencies on the base image would not be optimal as we would need to later remove them and that makes the final Docker image much larger in size than we want it to be.

**Comment by davidkarlsen** [comment]
Yes it would add a few mb - but also lower the entry-barrier if a customer could just pull your image of the hub and start running it (which also mean awesome upgrades)

**Comment by chamilad** [comment]
I agree on your point on how easy it would be for later processes, and it would be pretty cool being able to upgrade stuff by switching the base image underneath. However, I'm still not convinced enough that this should be done by the WSO2 common base image. 

Doesn't this sound more of an organizational level customization where there would be an organization-specific base image that gets inherited by customized wso2/docker-* Dockerfiles? Any idempotent configuration management tool would be able to handle already existing external dependencies.
